[build]
builder = "DOCKERFILE"
dockerfilePath = "/Dockerfile"
watchPatterns = [
  "/apps/admin/**",
  "/packages/**",
  "/Dockerfile",
  "/pnpm-lock.yaml",
  "/package.json",
  "/turbo.json",
]

[build.args]
APP = "admin"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
